// import './modules/animation.js'
// import './modules/diagram.js'
// import './modules/phase.js'
// import './modules/work.js'
import './modules/block-s.js'
import './modules/feature.js'
import './modules/benefit.js'
import './modules/diagram.js'
